"""Blender 4.5+/5.x. Paste into Scripting > New > Run Script.
Creates an original low-poly reconstruction of the supplied market-port reference.
No external assets, add-ons, or file paths required. One Blender unit = one metre.
Only a previous collection generated by this script is replaced.
"""
import bpy
import bmesh
import math
import random
from mathutils import Vector

NAME = 'ReferenceMarketHarbor'
SEED = 731
random.seed(SEED)
old = bpy.data.collections.get(NAME)
if old and old.get('generator') == NAME:
    for obj in list(old.all_objects):
        data = obj.data
        bpy.data.objects.remove(obj, do_unlink=True)
        if isinstance(data, bpy.types.Mesh) and data.users == 0:
            bpy.data.meshes.remove(data)
        elif isinstance(data, bpy.types.Camera) and data.users == 0:
            bpy.data.cameras.remove(data)
        elif isinstance(data, bpy.types.Light) and data.users == 0:
            bpy.data.lights.remove(data)
    for child in list(old.children):
        bpy.data.collections.remove(child)
    bpy.data.collections.remove(old)
collection = bpy.data.collections.new(NAME)
collection['generator'] = NAME
bpy.context.scene.collection.children.link(collection)
visuals = bpy.data.collections.new(NAME + '_Visuals')
collisions = bpy.data.collections.new(NAME + '_Collision')
studio = bpy.data.collections.new(NAME + '_Presentation')
for child in (visuals, collisions, studio):
    collection.children.link(child)
root = bpy.data.objects.new(NAME, None)
collection.objects.link(root)
root.location = (0, 0, 0)
root['units'] = 'metres'
root['reference_note'] = 'Visible proportions reconstructed; hidden sides inferred.'
palette = {
    'earth': '#745640', 'grass': '#879557', 'sand': '#b2a17a',
    'stone': '#93958a', 'trim': '#66503c', 'wood': '#96704d',
    'roof': '#826044', 'plaster': '#c6b58e', 'dark': '#343d39',
    'leaf': '#809950', 'leaf_light': '#a0ad64', 'water': '#6d9a9e',
    'red': '#b16f61', 'blue': '#668c9d', 'yellow': '#bdad65',
    'purple': '#967a9e', 'cream': '#d4c29c', 'green': '#77936b'
}
materials = []
indices = {}
def linear(v):
    return v / 12.92 if v <= .04045 else ((v + .055) / 1.055) ** 2.4
for name, value in palette.items():
    rgb = tuple(linear(int(value[i:i+2], 16) / 255) for i in (1, 3, 5))
    mat_name = NAME + '_' + name
    mat = bpy.data.materials.get(mat_name) or bpy.data.materials.new(mat_name)
    mat.use_nodes = True
    shader = mat.node_tree.nodes.get('Principled BSDF')
    shader.inputs['Base Color'].default_value = (*rgb, 1)
    shader.inputs['Roughness'].default_value = .87
    mat.diffuse_color = (*rgb, 1)
    indices[name] = len(materials)
    materials.append(mat)
buffers = {}
collider_count = 0
def data_mesh(name, vertices, faces):
    data = bpy.data.meshes.new(name)
    data.from_pydata(vertices, [], faces)
    data.validate(verbose=False)
    bm = bmesh.new()
    bm.from_mesh(data)
    bmesh.ops.remove_doubles(bm, verts=list(bm.verts), dist=.00001)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    bm.to_mesh(data)
    bm.free()
    data.update()
    for face in data.polygons:
        face.use_smooth = False
    return data
def emit(group, vertices, faces, color, collision=False):
    global collider_count
    if collision:
        collider_count += 1
        name = 'COL_%03d_%s' % (collider_count, group)
        obj = bpy.data.objects.new(name, data_mesh(name, vertices, faces))
        collisions.objects.link(obj)
        obj.parent = root
        obj.display_type = 'WIRE'
        obj.hide_render = True
        obj.hide_set(True)
        obj['collision_shape'] = 'CONVEX_MESH'
        return
    verts, polys, colors = buffers.setdefault(group, ([], [], []))
    offset = len(verts)
    verts.extend(vertices)
    polys.extend(tuple(offset + i for i in face) for face in faces)
    colors.extend([indices[color]] * len(faces) if isinstance(color,str) else [indices[c] for c in color])
def box(group, center, size, color, angle=0, collision=False):
    x, y, z = center
    w, d, h = (s / 2 for s in size)
    ca, sa = math.cos(angle), math.sin(angle)
    verts = [(x+a*ca-b*sa, y+a*sa+b*ca, z+c) for a,b,c in
             [(-w,-d,-h),(w,-d,-h),(w,d,-h),(-w,d,-h),
              (-w,-d,h),(w,-d,h),(w,d,h),(-w,d,h)]]
    faces = [(0,3,2,1),(4,5,6,7),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)]
    emit(group, verts, faces, color, collision)
def beam(group, a, b, radius, color, sides=6, end_radius=None, cap_start=True, cap_end=True):
    a, b = Vector(a), Vector(b)
    direction = b-a
    if direction.length < .0001:
        return
    direction.normalize()
    u = direction.cross(Vector((0,0,1)))
    if u.length < .001:
        u = direction.cross(Vector((0,1,0)))
    u.normalize()
    v = direction.cross(u)
    r2 = radius if end_radius is None else end_radius
    verts = [tuple(p + r*(u*math.cos(i*math.tau/sides)+v*math.sin(i*math.tau/sides)))
             for p,r in ((a,radius),(b,r2)) for i in range(sides)]
    faces = ([tuple(reversed(range(sides)))] if cap_start else [])
    if cap_end: faces.append(tuple(range(sides,2*sides)))
    faces += [(i,(i+1)%sides,(i+1)%sides+sides,i+sides) for i in range(sides)]
    emit(group, verts, faces, color)
def slab(group, outline, bottom, top, color, collider=True,top_color=None):
    n = len(outline)
    verts = [(x,y,z) for z in (bottom,top) for x,y in outline]
    faces = [tuple(reversed(range(n))), tuple(range(n,2*n))]
    faces += [(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
    emit(group, verts, faces, [color,top_color or color]+[color]*n)
    if collider:
        emit(group, verts, faces, color, True)
def ellipse(x,y,rx,ry,n=32):
    return [(x+rx*math.cos(i*math.tau/n),y+ry*math.sin(i*math.tau/n)) for i in range(n)]
def ring(group,x,y,z,outer,inner,height,color,n=24):
    verts = [(x+r*math.cos(i*math.tau/n),y+r*math.sin(i*math.tau/n),zz)
             for zz,r in ((z,outer),(z,inner),(z+height,outer),(z+height,inner)) for i in range(n)]
    faces = []
    for i in range(n):
        j=(i+1)%n
        faces += [(i,j,2*n+j,2*n+i),(n+j,n+i,3*n+i,3*n+j),
                  (2*n+i,2*n+j,3*n+j,3*n+i),(j,i,n+i,n+j)]
    emit(group,verts,faces,color)
def barrel(x,y,z,s=1):
    beam('Props',(x,y,z),(x,y,z+.55*s),.39*s,'wood',10,.49*s,cap_end=False)
    beam('Props',(x,y,z+.55*s),(x,y,z+1.1*s),.49*s,'wood',10,.39*s,cap_start=False)
    for h,r in ((.17,.445),(.85,.445)):
        ring('Props',x,y,z+h*s,r*s,(r-.05)*s,.10*s,'dark',10)
def crate(x,y,z,s=1,color='yellow'):
    box('Props',(x,y,z+s/2),(s,s,s),color)
    for dx in (-1,1):
        box('Props',(x+dx*(s/2-.07),y-s/2-.025,z+s/2),(.12,.08,s),'trim')
    for h in (.07,s-.07):
        box('Props',(x,y-s/2-.03,z+h),(s,.09,.12),'trim')
    beam('Props',(x-s*.35,y-s/2-.09,z+.18),(x+s*.35,y-s/2-.09,z+s-.18),.05,'trim',4)
def palm(x,y,z,h=6):
    lean = random.uniform(-.8,.8)
    beam('Palms',(x,y,z),(x+lean,y+.3,z+h),.24,'wood',7,.13)
    crown = Vector((x+lean,y+.3,z+h))
    for j in range(7):
        a=j*math.tau/7
        d=Vector((math.cos(a),math.sin(a),0)); s=Vector((-d.y,d.x,0))
        verts=[]
        for t,w in ((0,.04),(.35,.60),(.7,.40),(1,.015)):
            p=crown+d*t*3+Vector((0,0,math.sin(t*math.pi)-t*t))
            verts.extend([tuple(p-s*w),tuple(p+Vector((0,0,.10))),tuple(p+s*w)])
        faces=[]
        for i in range(3):
            k=i*3
            faces += [(k,k+3,k+4,k+1),(k+1,k+4,k+5,k+2)]
        # Thin closed leaf volumes, not coplanar duplicate backfaces.
        count=len(verts); verts += [(a,b,c-.035) for a,b,c in verts]
        original=list(faces)
        faces += [tuple(count+i for i in reversed(f)) for f in original]
        boundary=[0,3,6,9,10,11,8,5,2,1]
        faces += [(a,b,b+count,a+count) for a,b in zip(boundary,boundary[1:]+boundary[:1])]
        emit('Palms',verts,faces,'leaf_light' if j%2 else 'leaf')
def house(x,y,z,w=5.4,d=5,h=5.5,angle=0):
    ca,sa=math.cos(angle),math.sin(angle)
    def p(a,b,c): return (x+a*ca-b*sa,y+a*sa+b*ca,z+c)
    profile=[(-w/2,0),(w/2,0),(w/2,h),(0,h+2.1),(-w/2,h)]
    verts=[p(a,b,c) for b in (-d/2,d/2) for a,c in profile]
    faces=[(4,3,2,1,0),(5,6,7,8,9)]+[(i,(i+1)%5,(i+1)%5+5,i+5) for i in range(5)]
    emit('Buildings',verts,faces,'plaster')
    box('Buildings',p(0,0,.62),(w+.15,d+.15,1.24),'stone',angle)
    box('House',p(0,0,h/2),(w,d,h),'stone',angle,True)
    for side in (-1,1):
        roof=[p(0,-d/2-.4,h+2.25),p(side*(w/2+.5),-d/2-.4,h-.1),
              p(side*(w/2+.5),d/2+.4,h-.1),p(0,d/2+.4,h+2.25)]
        roof += [(a,b,c-.12) for a,b,c in roof]
        emit('Roofs',roof,[(0,1,2,3),(4,7,6,5),(0,4,5,1),(1,5,6,2),(2,6,7,3),(3,7,4,0)],'roof')
        beam('Timber',p(0,-d/2-.44,h+2.32),p(side*(w/2+.56),-d/2-.44,h-.06),.10,'trim',4)
    for xx in (-w/2+.08,0,w/2-.08):
        beam('Timber',p(xx,-d/2-.05,1.3),p(xx,-d/2-.05,h),.085,'trim',4)
    for zz in (1.3,3.1,h):
        box('Timber',p(0,-d/2-.075,zz),(w,.16,.15),'trim',angle)
    box('Details',p(-w*.22,-d/2-.10,1.35),(1.15,.14,2.1),'wood',angle)
    for xx in (-w*.27,w*.27):
        for zz in (3.95,h-.6):
            if zz < 3.5: continue
            box('Details',p(xx,-d/2-.10,zz),(.85,.14,1.05),'dark',angle)
            for dx in (-.48,0,.48):
                box('Details',p(xx+dx,-d/2-.20,zz),(.085,.1,1.16),'trim',angle)
            box('Details',p(xx,-d/2-.20,zz),(1.05,.1,.10),'trim',angle)
    box('Details',p(w*.28,d*.17,h+1.1),(.6,.65,1.8),'stone',angle)
    barrel(x-w*.6,y-1,z)
def stall(x,y,z,angle,color):
    ca,sa=math.cos(angle),math.sin(angle)
    def p(a,b,c): return (x+a*ca-b*sa,y+a*sa+b*ca,z+c)
    for a in (-1.55,1.55):
        for b in (-1.35,1.35):
            beam('Market',p(a,b,0),p(a,b,2.9 if b<0 else 3.5),.075,'trim',5)
    box('Market',p(0,-.75,.9),(3.0,.8,1.0),'wood',angle)
    for i in range(7):
        a=-1.75+i*.5; b=a+.498
        verts=[p(a,-1.65,2.85),p(b,-1.65,2.85),p(b,1.55,3.55),p(a,1.55,3.55)]
        verts += [(xx,yy,zz-.06) for xx,yy,zz in verts]
        emit('Awnings',verts,[(0,1,2,3),(4,7,6,5),(0,4,5,1),(1,5,6,2),(2,6,7,3),(3,7,4,0)],color if i%2==0 else 'cream')
    for a in (-.9,0,.9):
        beam('Goods',p(a,-.8,1.42),p(a,-.8,1.65),.24,random.choice(['red','green','yellow']),8,.14)
    barrel(x+1.95*ca,y+1.95*sa,z,.75)
def stairs(a,b,width=3.5):
    a,b=Vector(a),Vector(b); d=b-a; horizontal=Vector((d.x,d.y,0))
    length=horizontal.length; angle=math.atan2(d.y,d.x)
    count=max(1,math.ceil(abs(d.z)/.20))
    for i in range(count):
        t=(i+.5)/count; p=a.lerp(b,t)
        height=abs(d.z)*(i+1)/count+.15
        top=a.z+d.z*(i+1)/count
        box('Stairs',(p.x,p.y,top-height/2),(length/count-.006,width,height),'stone',angle)
    side=Vector((-d.y,d.x,0)).normalized()*width/2
    vs=[tuple(a-side),tuple(a+side),tuple(b+side),tuple(b-side)]
    vs += [(x,y,min(a.z,b.z)-.2) for x,y,z in vs]
    emit('StairRamp',vs,[(0,3,2,1),(4,5,6,7),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)],'stone',True)
def dock(y,length=18):
    start=-10; end=start-length
    for i in range(int(length/.45)):
        box('Docks',(start-i*.45-.22,y,1.22),(.43,4,.24),'wood')
    box('Dock',(start-length/2,y,1.2),(length,4,.30),'wood',collision=True)
    for x in range(int(end),int(start)+1,4):
        for side in (-1,1):
            beam('Docks',(x,y+side*1.78,-2),(x,y+side*1.78,1.85),.19,'wood',8)
    for x in (start-4,start-8):
        crate(x,y+.65,1.35,1.05,random.choice(['red','green','yellow']))
        barrel(x-1.4,y+.7,1.35,.8)
def boat(x,y,large=False):
    scale=1.65 if large else .78
    outline=[(0,-3.4),(1.1,-2.6),(1.3,-.5),(1.15,2.2),(.7,2.7),(-.7,2.7),(-1.15,2.2),(-1.3,-.5),(-1.1,-2.6)]
    n=len(outline)
    verts=[(x+a*scale*s,y+b*scale,z) for s,z in ((.72,-.35),(1,.9)) for a,b in outline]
    faces=[tuple(reversed(range(n))),tuple(range(n,2*n))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
    emit('Ships',verts,faces,'wood')
    for i in range(n):
        a,b=outline[i],outline[(i+1)%n]
        beam('Ships',(x+a[0]*scale,y+a[1]*scale,1),(x+b[0]*scale,y+b[1]*scale,1),.12,'cream',4)
    if large:
        for dy,h in ((-1.6,9),(1.4,7.6)):
            beam('Rigging',(x,y+dy,1),(x,y+dy,h),.12,'trim',8,.06)
            for z in (h*.5,h*.73,h*.92):
                beam('Rigging',(x-2,y+dy,z),(x+2,y+dy,z),.065,'wood',6)
            for sign in (-1,1):
                beam('Rigging',(x,y+dy,h-.4),(x+sign*1.7,y+dy+1.2,1),.025,'dark',4)
        crate(x,y+2,1,.9,'yellow')
    else:
        box('Ships',(x,y+.5,1.45),(1.25,1.55,1.0),'plaster')
        box('Ships',(x,y+.5,2.01),(1.5,1.85,.14),'blue')
        box('Ships',(x,y-.31,1.55),(.85,.10,.44),'dark')
def statue(x,y,z):
    box('Statues',(x,y,z+.2),(1.0,1.0,.4),'stone')
    box('Statues',(x,y,z+.75),(.6,.6,.7),'stone')
    beam('Statues',(x,y,z+1.1),(x,y,z+2.3),.3,'stone',6,.2)
    beam('Statues',(x,y,z+2.35),(x,y,z+2.8),.25,'stone',8,.15)

# Main D-shaped shoreline; separate elevations avoid coincident terrace surfaces.
outline=[(-10,-20),(0,-25),(17,-24),(29,-17),(34,-4),(31,12),(23,24),(6,29),(-8,23),(-13,12),(-12,-8)]
slab('Terrain',outline,-2.4,1.4,'earth',top_color='grass')
slab('Terraces',ellipse(9,1,14,10),1.43,4.22,'stone',top_color='sand')
rear=[(-8,16),(26,16),(28,21),(18,27),(3,28),(-8,23)]
slab('Terraces',rear,1.43,7.52,'stone',top_color='sand')
# Individual paving stones along the sweeping harbour promenade.
for i in range(42):
    a=math.radians(-174+i*4.8)
    for row in range(3):
        r=17.1+row*.83
        box('Paving',(9+math.cos(a)*r,1+math.sin(a)*r*.83,1.46),(1.14,.76,.12),'stone',a+math.pi/2)
stairs((-6,-13,1.47),(-4,-6,4.25),3.6)
stairs((25,-8,1.47),(21,-1,4.25),3.6)
stairs((8,8,4.25),(8,17,7.55),4.0)
stairs((29,5,1.47),(25,16,7.55),3.8)
for x,y,w,h,a in [(-4,21,5.6,6.7,-.12),(3,22,5.3,5.7,.02),(10,22,6.5,7.1,.02),(18,21,5.5,6.2,.15),(25,18.5,5.1,5.8,.38)]:
    house(x,y,7.52,w,4.8,h,a)
house(-8,12,1.4,3.6,3.4,2.9,-.15)
colors=['purple','blue','red','green','yellow']
for i,a in enumerate((-159,-133,-108,-82,-56,-30,3)):
    a=math.radians(a)
    stall(9+math.cos(a)*20.8,1+math.sin(a)*18.3,1.4,a-math.pi/2,colors[i%5])
for i,(x,y,a) in enumerate([(1,5,-.3),(7,6,0),(15,5,.2),(20,1,.8)]):
    stall(x,y,4.22,a,colors[(i+2)%5])
ring('Fountain',10,0,4.24,2.0,1.66,.52,'stone',24)
slab('FountainWater',ellipse(10,0,1.64,1.64,24),4.25,4.54,'water',False)
beam('Fountain',(10,0,4.55),(10,0,6.1),.33,'stone',10,.18)
ring('Fountain',10,0,5.8,1,.73,.2,'stone',16)
statue(10,0,6.0)
for x,y in [(5,-1),(15,-1),(-5,20),(24,23)]:
    statue(x,y,4.22 if y<0 else 7.52)
for p in [(-2,-1,4.22),(0,-2,4.22),(1,1,4.22),(-3,2,4.22),(-1,4,4.22),
          (-9,18,1.4),(-7,24,7.52),(0,26,7.52),(29,-9,1.4),(31,-3,1.4),(30,3,1.4)]:
    palm(*p,random.uniform(5,7))
for y,length in [(-16,19),(-4,20),(10,17),(20,13)]:
    dock(y,length)
for x,y,large in [(-34,-16,True),(-35,-3,True),(-31,11,True),(-24,22,False),(-24,-21,False),(-19,-9,False),(-19,5,False)]:
    boat(x,y,large)
# Harbour crane, cargo piles and coastal boulders.
for p in [(-16,-15,1.4),(-17,-3,1.4),(-13,11,1.4),(23,-16,1.4),(18,-11,1.4)]:
    x,y,z=p
    crate(x,y,z,1.2,'green'); crate(x,y,z+1.2,1.0,'red'); barrel(x+1.6,y,z)
for x in (-25,-22):
    beam('Crane',(x,-2,1.4),(x,-2,7),.2,'trim',6)
beam('Crane',(-26,-2,7.1),(-19,-2,7.1),.22,'wood',6)
beam('Crane',(-23,-2,7),(-23,-2,3.1),.03,'dark',4)
for x,y in [(-10,-20),(1,-26),(25,-21),(34,-6),(-13,3)]:
    beam('Rocks',(x,y,-.5),(x+.3,y+.1,1.9),1.4,'stone',6,.7)

for name,(verts,faces,colors_for_faces) in buffers.items():
    mesh=data_mesh(NAME+'_'+name,verts,faces)
    for material in materials:
        mesh.materials.append(material)
    for polygon,index in zip(mesh.polygons,colors_for_faces):
        polygon.material_index=index
    obj=bpy.data.objects.new(name,mesh)
    visuals.objects.link(obj); obj.parent=root
    obj['flat_shaded']=True
    # Coordinates are baked into vertices; every mesh keeps scale 1,1,1.
    obj.location=(0,0,0); obj.scale=(1,1,1)

scene=bpy.context.scene
scene.unit_settings.system='METRIC'; scene.unit_settings.scale_length=1
camera_data=bpy.data.cameras.new(NAME+'_Camera')
camera=bpy.data.objects.new(NAME+'_Camera',camera_data); studio.objects.link(camera)
camera.location=(65,-92,78)
camera.rotation_euler=(Vector((-1,1,5))-camera.location).to_track_quat('-Z','Y').to_euler()
camera_data.type='ORTHO'; camera_data.ortho_scale=102; scene.camera=camera
for name,position,energy,size in [('Key',(-35,-45,80),110000,55),('Fill',(45,10,55),65000,45)]:
    light=bpy.data.lights.new(NAME+'_'+name,'AREA'); light.energy=energy; light.size=size
    obj=bpy.data.objects.new(light.name,light); studio.objects.link(obj); obj.location=position
    obj.rotation_euler=(Vector((0,0,0))-obj.location).to_track_quat('-Z','Y').to_euler()
scene.render.resolution_x=1400; scene.render.resolution_y=1100; scene.render.resolution_percentage=100
scene.view_settings.view_transform='AgX'
bpy.ops.object.select_all(action='DESELECT')
root.select_set(True); bpy.context.view_layer.objects.active=root
if bpy.context.screen:
    for area in bpy.context.screen.areas:
        if area.type=='VIEW_3D':
            area.spaces.active.shading.type='MATERIAL'
            area.spaces.active.region_3d.view_perspective='CAMERA'
triangles=0
for obj in visuals.objects:
    obj.data.calc_loop_triangles(); triangles+=len(obj.data.loop_triangles)
root['visual_triangles']=triangles
root['collision_objects']=collider_count
print('%s: %d triangles, %d collision objects' % (NAME,triangles,collider_count))
